<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:id="_c0S1kAmnEeaYqaRqn1lxcQ" name="mmJavaMinimalista" nsURI="http://uniandes.edu.co/mmJavaMinimalista" nsPrefix="mmJavaMinimalista">
  <eAnnotations xmi:id="_c0S1kQmnEeaYqaRqn1lxcQ" source="genmymodel">
    <details xmi:id="_c0S1kgmnEeaYqaRqn1lxcQ" key="uuid" value="_7jvQUPYdEeWolbMxsR5EUQ"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_c0S1kwmnEeaYqaRqn1lxcQ" name="Package">
    <eAnnotations xmi:id="_c0S1lAmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S1lQmnEeaYqaRqn1lxcQ" key="uuid" value="_o0AHgNhMEDO0x4Or-3wTcQ"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S1lgmnEeaYqaRqn1lxcQ" name="subPackages" upperBound="-1" eType="_c0S1kwmnEeaYqaRqn1lxcQ" containment="true">
      <eAnnotations xmi:id="_c0S1lwmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S1mAmnEeaYqaRqn1lxcQ" key="uuid" value="_fv70ENhOEDOZdqnyCxo4tQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S1mgmnEeaYqaRqn1lxcQ" name="name">
      <eAnnotations xmi:id="_c0S1mwmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S1nAmnEeaYqaRqn1lxcQ" key="uuid" value="_UqUNsNhSEDOZdqnyCxo4tQ"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S1ngmnEeaYqaRqn1lxcQ" name="classes" upperBound="-1" eType="_c0S1sQmnEeaYqaRqn1lxcQ" containment="true">
      <eAnnotations xmi:id="_c0S1nwmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S1oAmnEeaYqaRqn1lxcQ" key="uuid" value="_OwVGENhTEDO0x4Or-3wTcQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S1ogmnEeaYqaRqn1lxcQ" name="interfaces" upperBound="-1" eType="_c0S11QmnEeaYqaRqn1lxcQ" containment="true">
      <eAnnotations xmi:id="_c0S1owmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S1pAmnEeaYqaRqn1lxcQ" key="uuid" value="_gD44kNhTEDO0x4Or-3wTcQ"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_c0S1pgmnEeaYqaRqn1lxcQ" name="Project">
    <eAnnotations xmi:id="_c0S1pwmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S1qAmnEeaYqaRqn1lxcQ" key="uuid" value="_KISysNhNEDOZdqnyCxo4tQ"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S1qQmnEeaYqaRqn1lxcQ" name="rootPackage" lowerBound="1" eType="_c0S1kwmnEeaYqaRqn1lxcQ" containment="true">
      <eAnnotations xmi:id="_c0S1qgmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S1qwmnEeaYqaRqn1lxcQ" key="uuid" value="_fcJ8cNhOEDO0x4Or-3wTcQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S1rQmnEeaYqaRqn1lxcQ" name="name">
      <eAnnotations xmi:id="_c0S1rgmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S1rwmnEeaYqaRqn1lxcQ" key="uuid" value="_Sg0xoNhSEDOZdqnyCxo4tQ"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_c0S1sQmnEeaYqaRqn1lxcQ" name="Class" eSuperTypes="_c0S2KgmnEeaYqaRqn1lxcQ">
    <eAnnotations xmi:id="_c0S1sgmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S1swmnEeaYqaRqn1lxcQ" key="uuid" value="_YdmEUNhNEDOZdqnyCxo4tQ"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S1tAmnEeaYqaRqn1lxcQ" name="extends" eType="_c0S1sQmnEeaYqaRqn1lxcQ">
      <eAnnotations xmi:id="_c0S1tQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S1tgmnEeaYqaRqn1lxcQ" key="uuid" value="_jNeR8NhOEDOZdqnyCxo4tQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S1uAmnEeaYqaRqn1lxcQ" name="annotateClass" upperBound="-1" eType="_c0S1_QmnEeaYqaRqn1lxcQ" containment="true">
      <eAnnotations xmi:id="_c0S1uQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S1ugmnEeaYqaRqn1lxcQ" key="uuid" value="_D1Ut4NhPEDOZdqnyCxo4tQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S1vAmnEeaYqaRqn1lxcQ" name="methods" upperBound="-1" eType="_c0S2LQmnEeaYqaRqn1lxcQ" containment="true">
      <eAnnotations xmi:id="_c0S1vQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S1vgmnEeaYqaRqn1lxcQ" key="uuid" value="_U3BUUNhPEDOZdqnyCxo4tQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S1wAmnEeaYqaRqn1lxcQ" name="attributes" upperBound="-1" eType="_c0S2CAmnEeaYqaRqn1lxcQ" containment="true">
      <eAnnotations xmi:id="_c0S1wQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S1wgmnEeaYqaRqn1lxcQ" key="uuid" value="_VudSoNhPEDOZdqnyCxo4tQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S1xAmnEeaYqaRqn1lxcQ" name="imports" upperBound="-1" eType="_c0S2SAmnEeaYqaRqn1lxcQ" containment="true">
      <eAnnotations xmi:id="_c0S1xQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S1xgmnEeaYqaRqn1lxcQ" key="uuid" value="_dNOxUNhPEDOZdqnyCxo4tQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S1yAmnEeaYqaRqn1lxcQ" name="name">
      <eAnnotations xmi:id="_c0S1yQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S1ygmnEeaYqaRqn1lxcQ" key="uuid" value="_Z1ggMNhSEDOZdqnyCxo4tQ"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S1zAmnEeaYqaRqn1lxcQ" name="visibility" eType="_c0S18QmnEeaYqaRqn1lxcQ">
      <eAnnotations xmi:id="_c0S1zQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S1zgmnEeaYqaRqn1lxcQ" key="uuid" value="_de3MgNhSEDOZdqnyCxo4tQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S10AmnEeaYqaRqn1lxcQ" name="implements" upperBound="-1" eType="_c0S11QmnEeaYqaRqn1lxcQ">
      <eAnnotations xmi:id="_c0S10QmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S10gmnEeaYqaRqn1lxcQ" key="uuid" value="_-fO2INhSEDO0x4Or-3wTcQ"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_c0S11QmnEeaYqaRqn1lxcQ" name="Interface">
    <eAnnotations xmi:id="_c0S11gmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S11wmnEeaYqaRqn1lxcQ" key="uuid" value="_cqrIwNhNEDOZdqnyCxo4tQ"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S12AmnEeaYqaRqn1lxcQ" name="name">
      <eAnnotations xmi:id="_c0S12QmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S12gmnEeaYqaRqn1lxcQ" key="uuid" value="_ViTloNhSEDO0x4Or-3wTcQ"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" xmi:id="_c0S13AmnEeaYqaRqn1lxcQ" name="Primitives">
    <eAnnotations xmi:id="_c0S13QmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S13gmnEeaYqaRqn1lxcQ" key="uuid" value="_le2UINhNEDOZdqnyCxo4tQ"/>
    </eAnnotations>
    <eLiterals xmi:id="_c0S13wmnEeaYqaRqn1lxcQ" name="int" literal="int">
      <eAnnotations xmi:id="_c0S14AmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S14QmnEeaYqaRqn1lxcQ" key="uuid" value="_7WIUANhOEDO0x4Or-3wTcQ"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals xmi:id="_c0S14gmnEeaYqaRqn1lxcQ" name="long" value="1" literal="long">
      <eAnnotations xmi:id="_c0S14wmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S15AmnEeaYqaRqn1lxcQ" key="uuid" value="_77gR8NhOEDO0x4Or-3wTcQ"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals xmi:id="_c0S15QmnEeaYqaRqn1lxcQ" name="float" value="2" literal="float">
      <eAnnotations xmi:id="_c0S15gmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S15wmnEeaYqaRqn1lxcQ" key="uuid" value="_mshWQNhPEDOZdqnyCxo4tQ"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals xmi:id="_c0S16AmnEeaYqaRqn1lxcQ" name="double" value="3" literal="double">
      <eAnnotations xmi:id="_c0S16QmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S16gmnEeaYqaRqn1lxcQ" key="uuid" value="_oW_UANhPEDOZdqnyCxo4tQ"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals xmi:id="_c0S16wmnEeaYqaRqn1lxcQ" name="boolean" value="4" literal="String">
      <eAnnotations xmi:id="_c0S17AmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S17QmnEeaYqaRqn1lxcQ" key="uuid" value="_uhqtkNhPEDOZdqnyCxo4tQ"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals xmi:id="_c0S17gmnEeaYqaRqn1lxcQ" name="char" value="5">
      <eAnnotations xmi:id="_c0S17wmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S18AmnEeaYqaRqn1lxcQ" key="uuid" value="_76FboOuUEDObKfMbV8vhfw"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" xmi:id="_c0S18QmnEeaYqaRqn1lxcQ" name="Visibility">
    <eAnnotations xmi:id="_c0S18gmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S18wmnEeaYqaRqn1lxcQ" key="uuid" value="_oltXYNhNEDOZdqnyCxo4tQ"/>
    </eAnnotations>
    <eLiterals xmi:id="_c0S19AmnEeaYqaRqn1lxcQ" name="public" literal="public">
      <eAnnotations xmi:id="_c0S19QmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S19gmnEeaYqaRqn1lxcQ" key="uuid" value="_8jjwcNhOEDO0x4Or-3wTcQ"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals xmi:id="_c0S19wmnEeaYqaRqn1lxcQ" name="protected" value="1">
      <eAnnotations xmi:id="_c0S1-AmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S1-QmnEeaYqaRqn1lxcQ" key="uuid" value="_9AoG8NhOEDO0x4Or-3wTcQ"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals xmi:id="_c0S1-gmnEeaYqaRqn1lxcQ" name="private" value="2" literal="private">
      <eAnnotations xmi:id="_c0S1-wmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S1_AmnEeaYqaRqn1lxcQ" key="uuid" value="_e6lD8NhPEDOZdqnyCxo4tQ"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_c0S1_QmnEeaYqaRqn1lxcQ" name="Annotation">
    <eAnnotations xmi:id="_c0S1_gmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S1_wmnEeaYqaRqn1lxcQ" key="uuid" value="_3JiNMNhNEDOZdqnyCxo4tQ"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S2AAmnEeaYqaRqn1lxcQ" name="name">
      <eAnnotations xmi:id="_c0S2AQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2AgmnEeaYqaRqn1lxcQ" key="uuid" value="_W8tHENhSEDOZdqnyCxo4tQ"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S2BAmnEeaYqaRqn1lxcQ" name="annotationParameters" upperBound="-1" eType="_c0S2eQmnEeaYqaRqn1lxcQ" containment="true">
      <eAnnotations xmi:id="_c0S2BQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2BgmnEeaYqaRqn1lxcQ" key="uuid" value="_FJws4Ou5EDOUsItWISc23Q"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_c0S2CAmnEeaYqaRqn1lxcQ" name="Attribute">
    <eAnnotations xmi:id="_c0S2CQmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S2CgmnEeaYqaRqn1lxcQ" key="uuid" value="_-EtPkNhNEDOZdqnyCxo4tQ"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S2CwmnEeaYqaRqn1lxcQ" name="annotateAttribute" upperBound="-1" eType="_c0S1_QmnEeaYqaRqn1lxcQ" containment="true">
      <eAnnotations xmi:id="_c0S2DAmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2DQmnEeaYqaRqn1lxcQ" key="uuid" value="_BIqTUNhPEDOZdqnyCxo4tQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S2DwmnEeaYqaRqn1lxcQ" name="name">
      <eAnnotations xmi:id="_c0S2EAmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2EQmnEeaYqaRqn1lxcQ" key="uuid" value="_XMq1sNhSEDO0x4Or-3wTcQ"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S2EwmnEeaYqaRqn1lxcQ" name="visibility" eType="_c0S18QmnEeaYqaRqn1lxcQ">
      <eAnnotations xmi:id="_c0S2FAmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2FQmnEeaYqaRqn1lxcQ" key="uuid" value="_YqgssNhSEDO0x4Or-3wTcQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S2FwmnEeaYqaRqn1lxcQ" name="datatypeAttribute" lowerBound="1" eType="_c0S2KgmnEeaYqaRqn1lxcQ">
      <eAnnotations xmi:id="_c0S2GAmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2GQmnEeaYqaRqn1lxcQ" key="uuid" value="_SHARgNhUEDO0x4Or-3wTcQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S2GwmnEeaYqaRqn1lxcQ" name="modifier" eType="_c0S2TwmnEeaYqaRqn1lxcQ" defaultValueLiteral="none">
      <eAnnotations xmi:id="_c0S2HAmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2HQmnEeaYqaRqn1lxcQ" key="uuid" value="_9k7IoOubEDObKfMbV8vhfw"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_c0S2HwmnEeaYqaRqn1lxcQ" name="Parameter">
    <eAnnotations xmi:id="_c0S2IAmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S2IQmnEeaYqaRqn1lxcQ" key="uuid" value="_Jp8NUNhOEDOZdqnyCxo4tQ"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S2IgmnEeaYqaRqn1lxcQ" name="datatypeParameter" lowerBound="1" eType="_c0S2KgmnEeaYqaRqn1lxcQ">
      <eAnnotations xmi:id="_c0S2IwmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2JAmnEeaYqaRqn1lxcQ" key="uuid" value="_ca2nQNhREDO0x4Or-3wTcQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S2JgmnEeaYqaRqn1lxcQ" name="name">
      <eAnnotations xmi:id="_c0S2JwmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2KAmnEeaYqaRqn1lxcQ" key="uuid" value="_kPtqsNhREDO0x4Or-3wTcQ"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_c0S2KgmnEeaYqaRqn1lxcQ" name="Classifier">
    <eAnnotations xmi:id="_c0S2KwmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S2LAmnEeaYqaRqn1lxcQ" key="uuid" value="_RktrgNhOEDO0x4Or-3wTcQ"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_c0S2LQmnEeaYqaRqn1lxcQ" name="Method">
    <eAnnotations xmi:id="_c0S2LgmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S2LwmnEeaYqaRqn1lxcQ" key="uuid" value="_7fKUMNhOEDOZdqnyCxo4tQ"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S2MAmnEeaYqaRqn1lxcQ" name="annotateMethod" upperBound="-1" eType="_c0S1_QmnEeaYqaRqn1lxcQ" containment="true">
      <eAnnotations xmi:id="_c0S2MQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2MgmnEeaYqaRqn1lxcQ" key="uuid" value="_CsdBUNhPEDOZdqnyCxo4tQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S2NAmnEeaYqaRqn1lxcQ" name="methodParameters" upperBound="-1" eType="_c0S2HwmnEeaYqaRqn1lxcQ" containment="true">
      <eAnnotations xmi:id="_c0S2NQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2NgmnEeaYqaRqn1lxcQ" key="uuid" value="_7Hmd4NhQEDOZdqnyCxo4tQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S2OAmnEeaYqaRqn1lxcQ" name="datatypeReturn" eType="_c0S2KgmnEeaYqaRqn1lxcQ">
      <eAnnotations xmi:id="_c0S2OQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2OgmnEeaYqaRqn1lxcQ" key="uuid" value="_e5J1sNhREDO0x4Or-3wTcQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S2PAmnEeaYqaRqn1lxcQ" name="name">
      <eAnnotations xmi:id="_c0S2PQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2PgmnEeaYqaRqn1lxcQ" key="uuid" value="_mLieMNhREDO0x4Or-3wTcQ"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S2QAmnEeaYqaRqn1lxcQ" name="visibility" eType="_c0S18QmnEeaYqaRqn1lxcQ">
      <eAnnotations xmi:id="_c0S2QQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2QgmnEeaYqaRqn1lxcQ" key="uuid" value="_oir7wNhREDO0x4Or-3wTcQ"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S2RAmnEeaYqaRqn1lxcQ" name="modifier" eType="_c0S2TwmnEeaYqaRqn1lxcQ" defaultValueLiteral="none">
      <eAnnotations xmi:id="_c0S2RQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2RgmnEeaYqaRqn1lxcQ" key="uuid" value="_LYF9kOucEDObKfMbV8vhfw"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_c0S2SAmnEeaYqaRqn1lxcQ" name="Import">
    <eAnnotations xmi:id="_c0S2SQmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S2SgmnEeaYqaRqn1lxcQ" key="uuid" value="_Y_4AENhPEDOZdqnyCxo4tQ"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S2SwmnEeaYqaRqn1lxcQ" name="name">
      <eAnnotations xmi:id="_c0S2TAmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2TQmnEeaYqaRqn1lxcQ" key="uuid" value="_Qh3xoNhSEDO0x4Or-3wTcQ"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" xmi:id="_c0S2TwmnEeaYqaRqn1lxcQ" name="Modifier">
    <eAnnotations xmi:id="_c0S2UAmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S2UQmnEeaYqaRqn1lxcQ" key="uuid" value="_ELG2oOuVEDObKfMbV8vhfw"/>
    </eAnnotations>
    <eLiterals xmi:id="_c0S2UgmnEeaYqaRqn1lxcQ" name="none" literal="none">
      <eAnnotations xmi:id="_c0S2UwmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2VAmnEeaYqaRqn1lxcQ" key="uuid" value="_MFTtEOuVEDObKfMbV8vhfw"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals xmi:id="_c0S2VQmnEeaYqaRqn1lxcQ" name="final" value="1" literal="final">
      <eAnnotations xmi:id="_c0S2VgmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2VwmnEeaYqaRqn1lxcQ" key="uuid" value="_OIZmMOuVEDObKfMbV8vhfw"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals xmi:id="_c0S2WAmnEeaYqaRqn1lxcQ" name="abstract" value="2" literal="abstract">
      <eAnnotations xmi:id="_c0S2WQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2WgmnEeaYqaRqn1lxcQ" key="uuid" value="_QQAy8OuVEDObKfMbV8vhfw"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals xmi:id="_c0S2WwmnEeaYqaRqn1lxcQ" name="synchronized" value="3" literal="synchronized">
      <eAnnotations xmi:id="_c0S2XAmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2XQmnEeaYqaRqn1lxcQ" key="uuid" value="_R4MRsOuVEDObKfMbV8vhfw"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals xmi:id="_c0S2XgmnEeaYqaRqn1lxcQ" name="static" value="4" literal="static">
      <eAnnotations xmi:id="_c0S2XwmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2YAmnEeaYqaRqn1lxcQ" key="uuid" value="_2y32IOvUEDOUsItWISc23Q"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_c0S2YQmnEeaYqaRqn1lxcQ" name="Primitive" eSuperTypes="_c0S2dQmnEeaYqaRqn1lxcQ">
    <eAnnotations xmi:id="_c0S2YgmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S2YwmnEeaYqaRqn1lxcQ" key="uuid" value="_HI1SYOudEDObKfMbV8vhfw"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S2ZAmnEeaYqaRqn1lxcQ" name="typeName" eType="_c0S13AmnEeaYqaRqn1lxcQ">
      <eAnnotations xmi:id="_c0S2ZQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2ZgmnEeaYqaRqn1lxcQ" key="uuid" value="_LhsJAOudEDObKfMbV8vhfw"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_c0S2aQmnEeaYqaRqn1lxcQ" name="Collection" eSuperTypes="_c0S2dQmnEeaYqaRqn1lxcQ">
    <eAnnotations xmi:id="_c0S2agmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S2awmnEeaYqaRqn1lxcQ" key="uuid" value="_S40uoOudEDObKfMbV8vhfw"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_c0S2bAmnEeaYqaRqn1lxcQ" name="datatype" lowerBound="1" eType="_c0S2KgmnEeaYqaRqn1lxcQ">
      <eAnnotations xmi:id="_c0S2bQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2bgmnEeaYqaRqn1lxcQ" key="uuid" value="_5GtJgOueEDObKfMbV8vhfw"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_c0S2cQmnEeaYqaRqn1lxcQ" name="List" eSuperTypes="_c0S2aQmnEeaYqaRqn1lxcQ">
    <eAnnotations xmi:id="_c0S2cgmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S2cwmnEeaYqaRqn1lxcQ" key="uuid" value="_Zy16cOudEDObKfMbV8vhfw"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_c0S2dQmnEeaYqaRqn1lxcQ" name="DataType" eSuperTypes="_c0S2KgmnEeaYqaRqn1lxcQ">
    <eAnnotations xmi:id="_c0S2dgmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S2dwmnEeaYqaRqn1lxcQ" key="uuid" value="_fpHhkOuuEDObKfMbV8vhfw"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_c0S2eQmnEeaYqaRqn1lxcQ" name="KeyValue">
    <eAnnotations xmi:id="_c0S2egmnEeaYqaRqn1lxcQ" source="genmymodel">
      <details xmi:id="_c0S2ewmnEeaYqaRqn1lxcQ" key="uuid" value="_2arpUOu4EDOUsItWISc23Q"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S2fAmnEeaYqaRqn1lxcQ" name="key">
      <eAnnotations xmi:id="_c0S2fQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2fgmnEeaYqaRqn1lxcQ" key="uuid" value="_5r0C4Ou4EDOUsItWISc23Q"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_c0S2gAmnEeaYqaRqn1lxcQ" name="value">
      <eAnnotations xmi:id="_c0S2gQmnEeaYqaRqn1lxcQ" source="genmymodel">
        <details xmi:id="_c0S2ggmnEeaYqaRqn1lxcQ" key="uuid" value="_6By58Ou4EDOUsItWISc23Q"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
